[package]
name = "chat"
version = "0.1.0"
edition = "2021"


[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["tls", "json"] }
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.6"
chrono = "0.4.23"
